### PR TITLE
Update dns_zoneedit.sh

### PR DESCRIPTION
**Pull request by onley**
move new validation to _zoneedit_api() {

### CODE REVIEW

**Comment by onley** [comment]
I apparently don't fully understand the pull mechanisms. The pull I did used my fork of dns_zoneedit.sh and added the validation to the _zoneedit_api() { sub but my version does not have the validation in the add and rm subs and the merge did not remove the validations there in main. I don't think it hurts but the _err message includes $cmd which is not set by the add and rm subs so there could be some undefined consequences. What did I need to do so that the merge removed lines in the main branch that I did not have in my fork? 

Actually looking closer execution will never reach the validation code in the add and rm subs as they return before getting there.

**Comment by blueslow** [comment]
I have merged your pull request, e.g added the `if ...` in the api function. I have also removed the superfluous `if _err ...` in the add and rm functions. Improved the pfsense installation documentation and patch for acme.inc. I have also tested this under pfsense. I will soon push to github. Please review dns_zoneedit.sh if OK then test standalone.

**Comment by onley** [comment]
Looks good and test good standalone here. Thank you for your work on this project. Definitely my new goto letsencrypt cert tool.

**Comment by blueslow** [comment]
Your welcome and you contributed. Happy holiday.

**Pull request merged**
