### PR TITLE
Update dns_zoneedit.sh

### PR DESCRIPTION
**Pull request by onley**
By moving the definition of the global url variables to the add and rm subs you can use the appropriate create or delete url. The rest of your code works for both the create and delete unmodified. I'm sure there are better ways to do this but this is what I came up with.

### CODE REVIEW

**Comment by blueslow** [comment]
Not tested but reviewed.

**Comment by onley** [comment]
I added some code I use in my ddns script with zoneedit to further validate a success create or delete. I just put it below the $? block you already have. 

`
  if [ "${response%%TEXT*}" != '<SUCCESS CODE="200" ' ]; then
    _err "error $domain $cmd $response"
    return 1
  fi

`

**Comment by blueslow** [comment]
I have now successfully tested the txt-delete.php endpoint in pfsense

I have merged the below at the end of the dns_zoneedit_add and dns_zoneedit_rm. I removed the `return 1` statement because the the functions already returned 1  below the if statement. I have not tested this and lacks capability to currently test this under pfsense.

```
if [ "${response%%TEXT*}" != '<SUCCESS CODE="200" ' ]; then
  _err "error $domain $cmd $response"
fi
```

**Comment by onley** [comment]
I'm sorry, that code was supposed to go in _zoneedit_api() { 
you don't have $cmd in the add and rm subs. Adding it in _zoneedit_api() { means that the add and rm subs will get a return value of 1 and their error checking can carry on from there. I will submit a pull.

**Pull request merged**
